listen              1935;
max_connections     1000;
daemon              off;

# HTTP服务（HLS/FLV）
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

# API（可选）
http_api {
    enabled         on;
    listen          1985;
}

# rtc_server {
#     enabled on;
#     listen 8000;
# }

vhost __defaultVhost__ {

    rtc {
        enabled off;
    }

    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }

    hls {
        enabled         on;

        # 存储路径
        hls_path        ./objs/nginx/html;

        hls_fragment    2;   
        hls_window      20;   

        hls_cleanup     on;
        hls_dispose     10;
    }
}
