#########################
# Active Competitive
#########################
de_dust2
de_mirage
de_inferno
de_nuke
de_overpass
de_vertigo
de_ancient
de_anubis

#########################
# Other Defuse
#########################
de_cache
de_train
de_cbble
de_canals
de_lake
de_safehouse
de_bank
de_stmarc
de_shortdust
de_shortnuke

#########################
# Hostage
#########################
cs_office
cs_italy

#########################
# Arms Race
#########################
ar_baggage
ar_shoots
ar_monastery
ar_pool_day
ar_lunacy

#########################
# Demolition
#########################
de_shorttrain
de_sugarcane
de_rialto

#########################
# Flying Scoutsman / Wingman
#########################
dz_blacksite
dz_sirocco
dz_junglety
dz_frostbite
dz_vineyard
dz_ember

#########################
# aim / 1v1 / Workshop
#########################
#workshop/2677944247/aim_map_nuke
#workshop/1901018709/aim_map
#workshop/2132241752/aim_dust1999
#workshop/2271217192/1v1_aim_prison
